micronaut:
  application:
    name: labsApi

netty:
  default:
    allocator:
      max-order: 3

graphql:
  enabled: true
  path: /graphql
  graphiql:
    enabled: true
    version: 0.13.2
    path: /graphiql
    template-path: classpath:graphiql/index.html
    template-parameters:
    page-title: GraphiQL

#datasources:
#  default:
#    url: ${JDBC_URL:`jdbc:mysql://localhost:3306/db`}
#    username: ${JDBC_USER:root}
#    password: ${JDBC_PASSWORD:}
#    dialect: MYSQL